// EmployeePersona — the finale of every teardown.
//
// The report ends not with "advice" but with a hire: a fully-formed AI
// employee tailored to THIS specific business. Cultural fit, languages,
// backstory, full skill matrix (inbound + proactive + outbound B2B), a
// day-in-the-life routine, and a salary comparison to the equivalent
// human team. The CTA is "Hire <FirstName>" — onboarding, not a demo.
//
// Persona is generated by /api/teardown via inferenceJsonChat with
// grounded context from the crawl, GBP, reviews, and social pulse.

"use client";

import type { ReactNode } from "react";

/* ─── Public type ─── */

export interface AgentSkill {
  category: "inbound" | "proactive" | "outbound";
  title: string;
  detail: string;
}

export interface AgentPersona {
  name: string;
  age: number;
  origin: string;
  languages: string[];
  backstory: string;
  fit: string;
  signature_line: string;
  skills: AgentSkill[];
  daily_routine: { time: string; action: string }[];
  references: string[];
  agent_cost_aed: number;
  human_equivalent: {
    title: string;
    salary_aed: number;
    benefits_aed: number;
  };
  ps_note?: string;
}

/* ─── Component ─── */

export function EmployeePersona({ persona }: { persona: AgentPersona }) {
  const firstName = persona.name.split(/\s+/)[0] || persona.name;
  const inbound = persona.skills.filter((s) => s.category === "inbound");
  const proactive = persona.skills.filter((s) => s.category === "proactive");
  const outbound = persona.skills.filter((s) => s.category === "outbound");
  const humanTotal = persona.human_equivalent.salary_aed + persona.human_equivalent.benefits_aed;
  const savings = Math.max(0, humanTotal - persona.agent_cost_aed);

  return (
    <section style={SX.section}>
      <div style={SX.sectionMeta}>
        <span>
          <span style={SX.idx}>§ Z</span> · your new employee
        </span>
        <span style={SX.mono}>HIRE-READY</span>
      </div>

      {/* Identity card */}
      <div style={SX.card}>
        <div style={SX.idHeader}>
          <div>
            <h2 style={SX.name}>{persona.name}</h2>
            <div style={SX.idMeta}>
              <span>{persona.age}</span>
              <span style={SX.dot} />
              <span>{persona.origin}</span>
              <span style={SX.dot} />
              <span>{persona.languages.join(" · ")}</span>
            </div>
          </div>
          <div style={SX.statusPill}>
            <span style={SX.statusDot} />
            ready to start
          </div>
        </div>

        <p style={SX.backstory}>{persona.backstory}</p>

        <blockquote style={SX.quote}>
          <span style={SX.quoteOpen}>“</span>
          {persona.signature_line}
          <span style={SX.quoteClose}>”</span>
        </blockquote>

        <div style={SX.fitBox}>
          <span style={SX.fitLabel}>WHY {firstName.toUpperCase()} FITS YOU</span>
          <p style={SX.fitText}>{persona.fit}</p>
        </div>
      </div>

      {/* Skills matrix */}
      <h3 style={SX.h3}>What {firstName} does for you</h3>
      <div style={SX.skillsGrid}>
        <SkillColumn
          title="Inbound"
          subtitle="when customers come to you"
          accent="#2d8e7d"
          accentBg="#dfeede"
          skills={inbound}
          emptyMsg="No inbound skills configured — that's a bug."
        />
        <SkillColumn
          title="Proactive"
          subtitle="keep the relationship alive"
          accent="#a07232"
          accentBg="#f4e4cb"
          skills={proactive}
          emptyMsg="No proactive skills configured."
        />
        <SkillColumn
          title="Outbound · B2B"
          subtitle="bring you new business"
          accent="#5d8a4a"
          accentBg="#e9f0dd"
          skills={outbound}
          emptyMsg="No outbound channels configured."
        />
      </div>

      {/* Daily routine */}
      <h3 style={SX.h3}>A day in {firstName}&apos;s life</h3>
      <div style={SX.routine}>
        {persona.daily_routine.map((r, i) => (
          <div key={i} style={SX.routineRow}>
            <span style={SX.routineTime}>{r.time}</span>
            <span style={SX.routineDot} />
            <span style={SX.routineAction}>{r.action}</span>
          </div>
        ))}
      </div>

      {/* Salary comparison */}
      <h3 style={SX.h3}>The math</h3>
      <div style={SX.compareGrid}>
        <CompareCard
          title="Human equivalent"
          subtitle={persona.human_equivalent.title}
          amount={humanTotal}
          detail={`AED ${persona.human_equivalent.salary_aed.toLocaleString()} salary + AED ${persona.human_equivalent.benefits_aed.toLocaleString()} benefits/visa/insurance`}
          muted
        />
        <CompareCard
          title={`Hiring ${firstName}`}
          subtitle="always on · never sick · speaks every language"
          amount={persona.agent_cost_aed}
          detail="All-in. Setup once, runs forever."
          muted={false}
        />
      </div>
      {savings > 0 && (
        <p style={SX.savings}>
          You save{" "}
          <strong style={{ color: "#1e6d3d" }}>
            AED {savings.toLocaleString()}/month
          </strong>
          {" "}— and gain a teammate who works 24/7/365 in {persona.languages.length} languages.
        </p>
      )}

      {/* References */}
      <h3 style={SX.h3}>References</h3>
      <ul style={SX.refs}>
        {persona.references.map((r, i) => (
          <li key={i} style={SX.refItem}>
            <span style={SX.refTick}>✓</span> {r}
          </li>
        ))}
      </ul>

      {/* CTA */}
      <div style={SX.ctaWrap}>
        <a href="/app/onboarding" style={SX.cta}>
          Hire {firstName} →
        </a>
        <span style={SX.ctaSub}>
          2-minute setup · pay AED 3,000 once + AED {persona.agent_cost_aed.toLocaleString()}/mo · cancel anytime
        </span>
      </div>

      {/* Hand-written P.S. — the personal touch at the bottom of the hire letter. */}
      {persona.ps_note && (
        <div style={SX.psWrap}>
          <span style={SX.psLabel}>P.S.</span>
          <p style={SX.psNote}>{persona.ps_note}</p>
          <span style={SX.psSignature}>— {firstName}</span>
        </div>
      )}
    </section>
  );
}

/* ─── Sub-components ─── */

function SkillColumn({
  title,
  subtitle,
  accent,
  accentBg,
  skills,
  emptyMsg,
}: {
  title: string;
  subtitle: string;
  accent: string;
  accentBg: string;
  skills: AgentSkill[];
  emptyMsg: string;
}) {
  return (
    <div style={SX.skillCol}>
      <div style={SX.skillColHeader}>
        <span style={{ ...SX.skillTag, background: accentBg, color: accent }}>{title}</span>
        <span style={SX.skillSub}>{subtitle}</span>
      </div>
      <div style={SX.skillList}>
        {skills.length === 0 && <p style={SX.skillEmpty}>{emptyMsg}</p>}
        {skills.map((s, i) => (
          <div key={i} style={SX.skillItem}>
            <div style={SX.skillTitle}>
              <span style={{ ...SX.skillBullet, background: accent }} />
              {s.title}
            </div>
            <p style={SX.skillDetail}>{s.detail}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

function CompareCard({
  title,
  subtitle,
  amount,
  detail,
  muted,
}: {
  title: string;
  subtitle: string;
  amount: number;
  detail: ReactNode;
  muted: boolean;
}) {
  return (
    <div
      style={{
        ...SX.compareCard,
        background: muted ? "#f4e4cb" : "#dfeede",
        borderColor: muted ? "#d4a460" : "#7ab063",
      }}
    >
      <span style={SX.compareTitle}>{title}</span>
      <span style={SX.compareSubtitle}>{subtitle}</span>
      <span style={{ ...SX.compareAmount, color: muted ? "#a07232" : "#1e6d3d" }}>
        AED {amount.toLocaleString()}
        <span style={SX.compareUnit}>/mo</span>
      </span>
      <span style={SX.compareDetail}>{detail}</span>
    </div>
  );
}

/* ─── Styles ─── */

const SERIF = "Instrument Serif, Georgia, serif";
const MONO =
  "ui-monospace, SFMono-Regular, 'JetBrains Mono', 'IBM Plex Mono', Menlo, Consolas, monospace";

const SX: Record<string, React.CSSProperties> = {
  section: {
    background: "var(--paper-card, #fbfaf4)",
    border: "1px solid var(--paper-line, #d8d2bf)",
    borderRadius: 8,
    padding: "32px 28px 28px",
    marginBottom: 20,
  },
  sectionMeta: {
    display: "flex",
    justifyContent: "space-between",
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--paper-mut, #837c69)",
    paddingBottom: 16,
    borderBottom: "1px solid var(--paper-line, #d8d2bf)",
    marginBottom: 22,
  },
  idx: { color: "var(--paper-ink, #1d1c18)" },
  mono: { fontFamily: MONO },

  card: {
    background: "var(--paper, #f6f3eb)",
    border: "1px solid var(--paper-line, #d8d2bf)",
    borderRadius: 8,
    padding: "26px 24px",
    marginBottom: 28,
  },
  idHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  name: {
    fontFamily: SERIF,
    fontSize: 44,
    fontWeight: 400,
    lineHeight: 1.05,
    margin: 0,
    color: "var(--paper-ink, #1d1c18)",
  },
  idMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 6,
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--paper-mut, #514c40)",
    flexWrap: "wrap",
  },
  dot: {
    width: 3,
    height: 3,
    borderRadius: "50%",
    background: "var(--paper-mut, #837c69)",
    display: "inline-block",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 12px",
    background: "#dfeede",
    color: "#1e6d3d",
    borderRadius: 999,
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#2d8e7d",
    display: "inline-block",
  },
  backstory: {
    fontSize: 15.5,
    lineHeight: 1.6,
    color: "var(--paper-ink, #1d1c18)",
    marginTop: 14,
    marginBottom: 18,
  },
  quote: {
    margin: "0 0 18px",
    padding: "14px 18px",
    background: "#fff",
    border: "1px solid var(--paper-line, #d8d2bf)",
    borderLeft: "3px solid #2d8e7d",
    borderRadius: 4,
    fontFamily: SERIF,
    fontSize: 19,
    fontStyle: "italic",
    color: "var(--paper-ink, #1d1c18)",
    lineHeight: 1.45,
  },
  quoteOpen: {
    color: "#2d8e7d",
    fontSize: 28,
    marginRight: 4,
    verticalAlign: "-4px",
  },
  quoteClose: {
    color: "#2d8e7d",
    fontSize: 28,
    marginLeft: 4,
    verticalAlign: "-4px",
  },
  fitBox: {
    marginTop: 4,
  },
  fitLabel: {
    display: "block",
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: "0.14em",
    color: "#2d8e7d",
    marginBottom: 4,
    fontWeight: 600,
  },
  fitText: {
    margin: 0,
    fontSize: 14.5,
    lineHeight: 1.55,
    color: "var(--paper-ink, #1d1c18)",
  },

  h3: {
    fontFamily: SERIF,
    fontSize: 26,
    fontWeight: 400,
    lineHeight: 1.1,
    margin: "0 0 16px",
    color: "var(--paper-ink, #1d1c18)",
  },

  /* skills */
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 14,
    marginBottom: 28,
  },
  skillCol: {
    background: "var(--paper, #f6f3eb)",
    border: "1px solid var(--paper-line, #d8d2bf)",
    borderRadius: 8,
    padding: "16px 18px 18px",
    display: "flex",
    flexDirection: "column",
  },
  skillColHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginBottom: 14,
    paddingBottom: 12,
    borderBottom: "1px dashed var(--paper-line, #d8d2bf)",
  },
  skillTag: {
    alignSelf: "flex-start",
    padding: "3px 10px",
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    borderRadius: 4,
    fontWeight: 600,
  },
  skillSub: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 14,
    color: "var(--paper-mut, #514c40)",
  },
  skillList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  skillItem: {
    padding: "8px 0",
  },
  skillTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--paper-ink, #1d1c18)",
  },
  skillBullet: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    display: "inline-block",
    flexShrink: 0,
  },
  skillDetail: {
    margin: "4px 0 0 13px",
    fontSize: 12.5,
    lineHeight: 1.55,
    color: "var(--paper-mut, #514c40)",
  },
  skillEmpty: {
    margin: 0,
    fontSize: 12.5,
    fontStyle: "italic",
    color: "var(--paper-mut, #837c69)",
  },

  /* routine */
  routine: {
    background: "var(--paper, #f6f3eb)",
    border: "1px solid var(--paper-line, #d8d2bf)",
    borderRadius: 8,
    padding: "8px 0",
    marginBottom: 28,
  },
  routineRow: {
    display: "grid",
    gridTemplateColumns: "70px 16px 1fr",
    alignItems: "baseline",
    gap: 10,
    padding: "10px 18px",
    borderBottom: "1px dashed var(--paper-line, #d8d2bf)",
  },
  routineTime: {
    fontFamily: MONO,
    fontSize: 12,
    letterSpacing: "0.06em",
    color: "#2d8e7d",
    fontWeight: 600,
  },
  routineDot: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    background: "#2d8e7d",
    alignSelf: "center",
  },
  routineAction: {
    fontSize: 13.5,
    lineHeight: 1.55,
    color: "var(--paper-ink, #1d1c18)",
  },

  /* compare */
  compareGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
    marginBottom: 12,
  },
  compareCard: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "18px 20px",
    border: "1px solid",
    borderRadius: 8,
  },
  compareTitle: {
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  compareSubtitle: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 14,
    color: "var(--paper-mut, #514c40)",
  },
  compareAmount: {
    fontFamily: SERIF,
    fontSize: 36,
    lineHeight: 1,
    marginTop: 4,
  },
  compareUnit: {
    fontFamily: MONO,
    fontSize: 13,
    marginLeft: 4,
    color: "var(--paper-mut, #837c69)",
  },
  compareDetail: {
    fontSize: 12,
    color: "var(--paper-mut, #514c40)",
    marginTop: 2,
  },
  savings: {
    margin: "8px 0 28px",
    fontSize: 14,
    color: "var(--paper-mut, #514c40)",
    lineHeight: 1.55,
  },

  /* references */
  refs: {
    listStyle: "none",
    padding: 0,
    margin: "0 0 28px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  refItem: {
    display: "flex",
    gap: 10,
    fontSize: 13,
    color: "var(--paper-mut, #514c40)",
    lineHeight: 1.5,
  },
  refTick: {
    color: "#2d8e7d",
    fontWeight: 700,
    flexShrink: 0,
  },

  /* cta */
  ctaWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    paddingTop: 8,
  },
  cta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "16px 36px",
    background: "#1d1c18",
    color: "#fbfaf4",
    fontFamily: SERIF,
    fontSize: 22,
    border: "none",
    borderRadius: 999,
    textDecoration: "none",
    fontStyle: "italic",
  },
  ctaSub: {
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: "0.06em",
    color: "var(--paper-mut, #837c69)",
    textAlign: "center",
  },

  /* P.S. — handwriting-style aside at the very bottom */
  psWrap: {
    marginTop: 32,
    paddingTop: 24,
    borderTop: "1px dashed var(--paper-line, #d8d2bf)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    transform: "rotate(-0.4deg)",
  },
  psLabel: {
    fontFamily: SERIF,
    fontSize: 18,
    fontStyle: "italic",
    color: "#2d8e7d",
    fontWeight: 600,
  },
  psNote: {
    fontFamily: SERIF,
    fontSize: 18,
    fontStyle: "italic",
    lineHeight: 1.55,
    color: "var(--paper-ink, #1d1c18)",
    margin: 0,
    maxWidth: "62ch",
  },
  psSignature: {
    fontFamily: SERIF,
    fontSize: 22,
    fontStyle: "italic",
    color: "#2d8e7d",
    transform: "rotate(-1.5deg)",
    transformOrigin: "left center",
    marginTop: 4,
  },
};
