// PlatformDemo — eight sections that turn the teardown from "analysis"
// into "demonstration of platform surface area". Each one maps to a real
// capability we've built and that prospects can't get from any agency:
//
//   1. CustomerMemoryCard       → Mem0/Graphiti persistent profile
//   2. OwnerBriefCard           → Owner Brain morning SCQA brief
//   3. VoiceNoteDemoCard        → AR voice → 1.2s transcription → reply
//   4. B2BPipelineCard          → Sales Rep / SDR agent (5 named leads)
//   5. SevenDayPlanCard         → Day-by-day agent calendar
//   6. RevenueProjectionCard    → Math grounded in their real numbers
//   7. ChannelMapCard           → Multi-channel orchestrator topology
//   8. NightlyLearningCard      → Karpathy self-improving loop
//
// Each is optional on TeardownPackage (older permalinks won't have them).
// Generated by a single inferenceJsonChat in the orchestrator.

"use client";

import type { ReactNode } from "react";
import type { AgentPersona } from "./employee-persona";

/* ─── Types ─── */

export interface CustomerMemoryDemo {
  customer_name: string;
  customer_initial: string;
  status: string;
  highlights: { k: string; v: string }[];
  sentiment_history: string;
  next_action: string;
}

export interface OwnerMorningBrief {
  greeting: string;
  date_line: string;
  situation: string;
  complication: string;
  question: string;
  action_options: string[];
  numbers: { k: string; v: string }[];
}

export interface VoiceNoteDemo {
  voice_lang: string;
  voice_duration_s: number;
  customer_speech_translated: string;
  agent_transcription: string;
  agent_reply: string;
  agent_reply_lang: string;
  processing_ms: number;
}

export interface B2BLead {
  target_name: string;
  target_type: string;
  target_url?: string | null;
  why_fit: string;
  channel: "email" | "linkedin" | "instagram_dm" | "whatsapp";
  drafted_message: string;
  offer: string;
}

export interface B2BPipeline {
  leads: B2BLead[];
  monday_action: string;
}

export interface DayPlan {
  day: number;
  label: string;
  inbound: string[];
  proactive: string[];
  outbound: string[];
}

export interface SevenDayPlan {
  days: DayPlan[];
  summary_stat: string;
}

export interface RevenueScenario {
  name: string;
  math: string;
  monthly_aed: number;
  confidence: "conservative" | "moderate" | "optimistic";
}

export interface RevenueProjection {
  ground_truth: { k: string; v: string }[];
  scenarios: RevenueScenario[];
  total_conservative_aed: number;
  total_optimistic_aed: number;
  agent_cost_aed: number;
}

export interface ChannelEntry {
  name: string;
  status: "live" | "ready" | "coming";
  inbound_rate_estimate: string;
  sample_action: string;
}

export interface ChannelMap {
  channels: ChannelEntry[];
  unique_value: string;
}

export interface NightlyStep {
  time: string;
  label: string;
  detail: string;
}

export interface NightlyLearning {
  timeline: NightlyStep[];
  example_rule_drafted: string;
  example_rule_verified: string;
  result: string;
}

export interface PlatformDemo {
  customer_memory?: CustomerMemoryDemo | null;
  owner_brief?: OwnerMorningBrief | null;
  voice_demo?: VoiceNoteDemo | null;
  b2b_pipeline?: B2BPipeline | null;
  seven_day_plan?: SevenDayPlan | null;
  revenue_projection?: RevenueProjection | null;
  channel_map?: ChannelMap | null;
  nightly_learning?: NightlyLearning | null;
}

/* ─── Shared chrome ─── */

const SERIF = "Instrument Serif, Georgia, serif";
const MONO =
  "ui-monospace, SFMono-Regular, 'JetBrains Mono', 'IBM Plex Mono', Menlo, Consolas, monospace";

function Section({
  idx,
  label,
  right,
  children,
  dark = false,
}: {
  idx: string;
  label: string;
  right?: ReactNode;
  children: ReactNode;
  dark?: boolean;
}) {
  return (
    <section
      style={{
        background: dark ? "#15151a" : "var(--paper-card, #fbfaf4)",
        border: dark ? "1px solid #2a2a36" : "1px solid var(--paper-line, #d8d2bf)",
        color: dark ? "#f3f1ea" : "var(--paper-ink, #1d1c18)",
        borderRadius: 8,
        padding: "26px 24px 22px",
        marginBottom: 20,
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          fontFamily: MONO,
          fontSize: 11,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: dark ? "rgba(255,255,255,0.55)" : "var(--paper-mut, #837c69)",
          paddingBottom: 14,
          borderBottom: dark
            ? "1px solid #2a2a36"
            : "1px solid var(--paper-line, #d8d2bf)",
          marginBottom: 18,
          gap: 12,
          flexWrap: "wrap",
        }}
      >
        <span>
          § {idx} · {label}
        </span>
        {right && <span>{right}</span>}
      </div>
      {children}
    </section>
  );
}

/* ─── 1. CustomerMemoryCard ─── */

export function CustomerMemoryCard({
  memory,
  agentName,
}: {
  memory: CustomerMemoryDemo;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="I"
      label="what I already know"
      right={<span>customer memory · spans years</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        Meet a customer{" "}
        <em style={{ color: "#2d8e7d" }}>I&apos;ll already recognise on day one.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        From your reviews and booking patterns, this is the kind of profile {firstName} writes
        and remembers across every channel — forever.
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0, 280px) 1fr",
          gap: 22,
          alignItems: "start",
        }}
      >
        {/* Memory card visual */}
        <div
          style={{
            background: "var(--paper, #f6f3eb)",
            border: "1px solid var(--paper-line, #d8d2bf)",
            borderRadius: 8,
            padding: "16px 18px",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
            <div
              style={{
                width: 42,
                height: 42,
                borderRadius: "50%",
                background: "#2d8e7d",
                color: "#fbfaf4",
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                fontFamily: SERIF,
                fontSize: 22,
                fontStyle: "italic",
              }}
            >
              {memory.customer_initial}
            </div>
            <div style={{ flex: 1 }}>
              <div
                style={{
                  fontFamily: SERIF,
                  fontSize: 18,
                  fontWeight: 400,
                  color: "var(--paper-ink, #1d1c18)",
                }}
              >
                {memory.customer_name}
              </div>
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 10,
                  letterSpacing: "0.1em",
                  textTransform: "uppercase",
                  color: "#2d8e7d",
                }}
              >
                {memory.status}
              </div>
            </div>
          </div>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <tbody>
              {memory.highlights.map((h, i) => (
                <tr key={i}>
                  <td
                    style={{
                      padding: "5px 0",
                      fontFamily: MONO,
                      fontSize: 10,
                      letterSpacing: "0.1em",
                      textTransform: "uppercase",
                      color: "var(--paper-mut, #837c69)",
                      verticalAlign: "top",
                      width: 90,
                    }}
                  >
                    {h.k}
                  </td>
                  <td
                    style={{
                      padding: "5px 0",
                      fontSize: 13,
                      color: "var(--paper-ink, #1d1c18)",
                    }}
                  >
                    {h.v}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Right side: sentiment trail + next action */}
        <div>
          <h4
            style={{
              fontFamily: MONO,
              fontSize: 10,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "var(--paper-mut, #837c69)",
              margin: "0 0 6px",
            }}
          >
            Sentiment trail
          </h4>
          <p
            style={{
              fontSize: 14,
              lineHeight: 1.55,
              margin: "0 0 18px",
              color: "var(--paper-ink, #1d1c18)",
            }}
          >
            {memory.sentiment_history}
          </p>
          <h4
            style={{
              fontFamily: MONO,
              fontSize: 10,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "#2d8e7d",
              margin: "0 0 6px",
            }}
          >
            Next action {firstName} would take
          </h4>
          <p
            style={{
              fontFamily: SERIF,
              fontSize: 17,
              fontStyle: "italic",
              lineHeight: 1.4,
              margin: 0,
              color: "var(--paper-ink, #1d1c18)",
            }}
          >
            {memory.next_action}
          </p>
        </div>
      </div>
    </Section>
  );
}

/* ─── 2. OwnerBriefCard ─── */

export function OwnerBriefCard({
  brief,
  agentName,
}: {
  brief: OwnerMorningBrief;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="II"
      label="your 9am brief"
      right={<span>owner brain · daily SCQA</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        What you&apos;d find on your WhatsApp{" "}
        <em style={{ color: "#2d8e7d" }}>tomorrow at 9:00am</em>.
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        Situation, complication, question, action — the McKinsey framework, every morning.
        Variance detection flags what changed.
      </p>

      <div
        style={{
          background: "#075e54",
          color: "#fff",
          borderRadius: 12,
          padding: "16px 18px",
          maxWidth: 560,
          marginBottom: 14,
          boxShadow: "0 4px 14px rgba(7, 94, 84, 0.18)",
        }}
      >
        <div
          style={{
            fontFamily: MONO,
            fontSize: 10,
            letterSpacing: "0.12em",
            opacity: 0.7,
            marginBottom: 10,
          }}
        >
          {firstName.toLowerCase()} · owner brain · whatsapp · 09:00
        </div>
        <p style={{ fontFamily: SERIF, fontSize: 19, lineHeight: 1.35, margin: "0 0 8px" }}>
          {brief.greeting}
        </p>
        <p
          style={{
            fontFamily: MONO,
            fontSize: 11,
            letterSpacing: "0.1em",
            opacity: 0.7,
            margin: "0 0 14px",
          }}
        >
          {brief.date_line}
        </p>
        <BriefBlock label="Situation" body={brief.situation} />
        <BriefBlock label="Complication" body={brief.complication} />
        <BriefBlock label="Question" body={brief.question} accent />
        {brief.action_options.length > 0 && (
          <div style={{ marginTop: 10, display: "flex", flexDirection: "column", gap: 6 }}>
            {brief.action_options.slice(0, 4).map((opt, i) => (
              <span
                key={i}
                style={{
                  display: "inline-block",
                  padding: "8px 14px",
                  background: "rgba(255,255,255,0.12)",
                  borderRadius: 999,
                  fontSize: 13,
                  fontFamily: SERIF,
                  fontStyle: "italic",
                }}
              >
                {String.fromCharCode(65 + i)}. {opt}
              </span>
            ))}
          </div>
        )}
      </div>

      {brief.numbers.length > 0 && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
            gap: 12,
          }}
        >
          {brief.numbers.slice(0, 5).map((n, i) => (
            <div
              key={i}
              style={{
                background: "var(--paper, #f6f3eb)",
                border: "1px solid var(--paper-line, #d8d2bf)",
                borderRadius: 6,
                padding: "10px 14px",
              }}
            >
              <div
                style={{
                  fontFamily: SERIF,
                  fontSize: 24,
                  color: "var(--paper-ink, #1d1c18)",
                  lineHeight: 1,
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {n.v}
              </div>
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 9,
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color: "var(--paper-mut, #837c69)",
                  marginTop: 6,
                }}
              >
                {n.k}
              </div>
            </div>
          ))}
        </div>
      )}
    </Section>
  );
}

function BriefBlock({
  label,
  body,
  accent,
}: {
  label: string;
  body: string;
  accent?: boolean;
}) {
  return (
    <div style={{ marginBottom: 10 }}>
      <div
        style={{
          fontFamily: MONO,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: accent ? "#fbbf24" : "rgba(255,255,255,0.55)",
          marginBottom: 3,
        }}
      >
        {label}
      </div>
      <p style={{ fontSize: 14, lineHeight: 1.5, margin: 0 }}>{body}</p>
    </div>
  );
}

/* ─── 3. VoiceNoteDemoCard ─── */

export function VoiceNoteDemoCard({
  demo,
  agentName,
}: {
  demo: VoiceNoteDemo;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="III"
      label="voice notes work"
      right={<span>arabic transcription · {demo.processing_ms}ms</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        A customer sends a 12-second voice note.{" "}
        <em style={{ color: "#2d8e7d" }}>{firstName} answers in {(demo.processing_ms / 1000).toFixed(1)}s.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        Native Gulf Arabic in, native Gulf Arabic out. Or English. Or both — {firstName} picks
        the language the customer used.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 10, maxWidth: 540 }}>
        {/* Customer voice note */}
        <div style={{ alignSelf: "flex-start", maxWidth: "85%" }}>
          <div
            style={{
              background: "#fff",
              border: "1px solid var(--paper-line, #d8d2bf)",
              borderRadius: "10px 10px 10px 2px",
              padding: "10px 14px",
              fontFamily: MONO,
              fontSize: 12,
              color: "var(--paper-mut, #514c40)",
              display: "flex",
              alignItems: "center",
              gap: 10,
            }}
          >
            <WaveformIcon />
            <span>voice note · {demo.voice_duration_s}s · {demo.voice_lang}</span>
            <span style={{ fontFamily: MONO, marginLeft: "auto" }}>▶</span>
          </div>
          <p
            style={{
              fontSize: 12,
              fontStyle: "italic",
              color: "var(--paper-mut, #837c69)",
              margin: "4px 0 0 6px",
            }}
          >
            &ldquo;{demo.customer_speech_translated}&rdquo;
          </p>
        </div>

        {/* Transcription block (agent's internal step) */}
        <div
          style={{
            margin: "4px 0",
            padding: "10px 14px",
            background: "rgba(45,142,125,0.08)",
            border: "1px solid rgba(45,142,125,0.3)",
            borderLeft: "3px solid #2d8e7d",
            borderRadius: 6,
          }}
        >
          <div
            style={{
              fontFamily: MONO,
              fontSize: 9,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "#2d8e7d",
              marginBottom: 4,
            }}
          >
            {firstName} transcribes → {demo.processing_ms}ms
          </div>
          <p
            style={{
              fontFamily: SERIF,
              fontSize: 14,
              fontStyle: "italic",
              margin: 0,
              color: "var(--paper-ink, #1d1c18)",
              lineHeight: 1.45,
            }}
          >
            {demo.agent_transcription}
          </p>
        </div>

        {/* Agent reply */}
        <div style={{ alignSelf: "flex-end", maxWidth: "85%" }}>
          <div
            style={{
              background: "#dcf8c6",
              border: "1px solid rgba(0,0,0,0.06)",
              borderRadius: "10px 10px 2px 10px",
              padding: "10px 14px",
              fontSize: 13,
              lineHeight: 1.45,
              color: "#0c2018",
            }}
          >
            {demo.agent_reply}
          </div>
          <div
            style={{
              textAlign: "right",
              fontFamily: MONO,
              fontSize: 10,
              color: "var(--paper-mut, #837c69)",
              marginTop: 3,
            }}
          >
            {firstName.toLowerCase()} · {demo.agent_reply_lang} · ✓✓
          </div>
        </div>
      </div>
    </Section>
  );
}

function WaveformIcon() {
  return (
    <svg
      width="48"
      height="14"
      viewBox="0 0 48 14"
      fill="none"
      style={{ flexShrink: 0 }}
      aria-hidden
    >
      {[3, 6, 9, 11, 7, 12, 5, 10, 4, 8, 13, 6, 9, 4].map((h, i) => (
        <rect
          key={i}
          x={i * 3.4}
          y={7 - h / 2}
          width="1.8"
          height={h}
          fill="#2d8e7d"
          rx="0.6"
        />
      ))}
    </svg>
  );
}

/* ─── 4. B2BPipelineCard ─── */

export function B2BPipelineCard({
  pipeline,
  agentName,
}: {
  pipeline: B2BPipeline;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  const channelLabel: Record<B2BLead["channel"], string> = {
    email: "Email",
    linkedin: "LinkedIn DM",
    instagram_dm: "Instagram DM",
    whatsapp: "WhatsApp",
  };
  const channelColor: Record<B2BLead["channel"], string> = {
    email: "#5d8a4a",
    linkedin: "#1f6b9a",
    instagram_dm: "#a83a7a",
    whatsapp: "#1e6d3d",
  };
  return (
    <Section
      idx="IV"
      label="new business by monday"
      right={<span>sales rep · {pipeline.leads.length} drafted leads</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        {pipeline.leads.length} doors{" "}
        <em style={{ color: "#2d8e7d" }}>I&apos;d open for you next week.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        Each one researched, matched to your brand, with a personalised invitation in {firstName}
        &apos;s voice. You approve once, all five go out — and {firstName} tracks the responses.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        {pipeline.leads.map((lead, i) => (
          <div
            key={i}
            style={{
              border: "1px solid var(--paper-line, #d8d2bf)",
              borderRadius: 8,
              padding: "16px 18px",
              background: "var(--paper, #f6f3eb)",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "flex-start",
                gap: 12,
                marginBottom: 8,
                flexWrap: "wrap",
              }}
            >
              <div style={{ flex: "1 1 240px" }}>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10,
                    flexWrap: "wrap",
                  }}
                >
                  <div
                    style={{
                      fontFamily: SERIF,
                      fontSize: 20,
                      fontWeight: 400,
                      lineHeight: 1.2,
                      color: "var(--paper-ink, #1d1c18)",
                    }}
                  >
                    {lead.target_name}
                  </div>
                  {lead.target_url && (
                    <span
                      style={{
                        display: "inline-flex",
                        alignItems: "center",
                        gap: 4,
                        padding: "2px 8px",
                        background: "#dfeede",
                        color: "#1e6d3d",
                        borderRadius: 4,
                        fontFamily: MONO,
                        fontSize: 9,
                        letterSpacing: "0.14em",
                        textTransform: "uppercase",
                        fontWeight: 700,
                      }}
                    >
                      ● verified
                    </span>
                  )}
                </div>
                <div
                  style={{
                    fontFamily: MONO,
                    fontSize: 11,
                    letterSpacing: "0.06em",
                    color: "var(--paper-mut, #837c69)",
                    marginTop: 2,
                  }}
                >
                  {lead.target_type}
                </div>
                {lead.target_url && (
                  <a
                    href={lead.target_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      display: "inline-block",
                      marginTop: 4,
                      fontFamily: MONO,
                      fontSize: 11,
                      color: "#2d8e7d",
                      textDecoration: "underline",
                      textDecorationColor: "rgba(45,142,125,0.4)",
                      textUnderlineOffset: 2,
                      maxWidth: "100%",
                      wordBreak: "break-all",
                    }}
                  >
                    {lead.target_url.replace(/^https?:\/\//, "").replace(/\/$/, "").slice(0, 60)}
                    {lead.target_url.length > 60 ? "…" : ""}
                  </a>
                )}
              </div>
              <span
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "4px 10px",
                  background: channelColor[lead.channel] + "1A",
                  color: channelColor[lead.channel],
                  borderRadius: 999,
                  fontFamily: MONO,
                  fontSize: 10,
                  letterSpacing: "0.1em",
                  textTransform: "uppercase",
                  fontWeight: 600,
                  flexShrink: 0,
                }}
              >
                via {channelLabel[lead.channel]}
              </span>
            </div>
            <p
              style={{
                fontFamily: SERIF,
                fontStyle: "italic",
                fontSize: 14,
                color: "var(--paper-mut, #514c40)",
                margin: "0 0 12px",
                lineHeight: 1.5,
              }}
            >
              Why fit: {lead.why_fit}
            </p>
            <div
              style={{
                background: "#fff",
                border: "1px solid var(--paper-line, #d8d2bf)",
                borderRadius: 6,
                padding: "12px 14px",
                marginBottom: 10,
              }}
            >
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 9,
                  letterSpacing: "0.14em",
                  textTransform: "uppercase",
                  color: "#2d8e7d",
                  marginBottom: 6,
                }}
              >
                Drafted by {firstName}
              </div>
              <p
                style={{
                  fontSize: 13.5,
                  lineHeight: 1.55,
                  whiteSpace: "pre-wrap",
                  margin: 0,
                  color: "var(--paper-ink, #1d1c18)",
                }}
              >
                {lead.drafted_message}
              </p>
            </div>
            <div
              style={{
                display: "inline-block",
                padding: "5px 12px",
                background: "#dfeede",
                color: "#1e6d3d",
                borderRadius: 6,
                fontSize: 12,
                fontFamily: MONO,
                fontWeight: 600,
              }}
            >
              Offer: {lead.offer}
            </div>
          </div>
        ))}
      </div>

      <p
        style={{
          marginTop: 18,
          fontFamily: SERIF,
          fontSize: 17,
          fontStyle: "italic",
          color: "var(--paper-ink, #1d1c18)",
        }}
      >
        ↳ {pipeline.monday_action}
      </p>
    </Section>
  );
}

/* ─── 5. SevenDayPlanCard ─── */

export function SevenDayPlanCard({
  plan,
  agentName,
}: {
  plan: SevenDayPlan;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="V"
      label="your first 7 days"
      right={<span>day-by-day calendar</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        Week one with{" "}
        <em style={{ color: "#2d8e7d" }}>{firstName} on the team.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        Every day mixes inbound (customers who come to you), proactive (keep relationships
        alive), and outbound (bring new business in).
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
          gap: 14,
        }}
      >
        {plan.days.slice(0, 7).map((d) => (
          <div
            key={d.day}
            style={{
              background: "var(--paper, #f6f3eb)",
              border: "1px solid var(--paper-line, #d8d2bf)",
              borderRadius: 8,
              padding: "14px 16px",
              display: "flex",
              flexDirection: "column",
              gap: 10,
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "baseline",
                paddingBottom: 8,
                borderBottom: "1px dashed var(--paper-line, #d8d2bf)",
              }}
            >
              <span
                style={{
                  fontFamily: SERIF,
                  fontSize: 22,
                  lineHeight: 1,
                  color: "var(--paper-ink, #1d1c18)",
                }}
              >
                {d.label}
              </span>
              <span
                style={{
                  fontFamily: MONO,
                  fontSize: 10,
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color: "var(--paper-mut, #837c69)",
                }}
              >
                day {d.day}
              </span>
            </div>

            <DayActionList label="inbound" items={d.inbound} accent="#2d8e7d" />
            <DayActionList label="proactive" items={d.proactive} accent="#a07232" />
            <DayActionList label="outbound" items={d.outbound} accent="#5d8a4a" />
          </div>
        ))}
      </div>

      <p
        style={{
          marginTop: 18,
          fontFamily: SERIF,
          fontSize: 17,
          fontStyle: "italic",
          color: "var(--paper-ink, #1d1c18)",
        }}
      >
        ↳ {plan.summary_stat}
      </p>
    </Section>
  );
}

function DayActionList({
  label,
  items,
  accent,
}: {
  label: string;
  items: string[];
  accent: string;
}) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <div
        style={{
          fontFamily: MONO,
          fontSize: 9,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          color: accent,
          marginBottom: 4,
          fontWeight: 600,
        }}
      >
        {label}
      </div>
      <ul style={{ margin: 0, padding: 0, listStyle: "none" }}>
        {items.slice(0, 4).map((it, i) => (
          <li
            key={i}
            style={{
              fontSize: 12.5,
              lineHeight: 1.5,
              color: "var(--paper-ink, #1d1c18)",
              paddingLeft: 12,
              position: "relative",
            }}
          >
            <span
              style={{
                position: "absolute",
                left: 0,
                top: 8,
                width: 4,
                height: 4,
                background: accent,
                borderRadius: "50%",
              }}
            />
            {it}
          </li>
        ))}
      </ul>
    </div>
  );
}

/* ─── 6. RevenueProjectionCard ─── */

export function RevenueProjectionCard({
  proj,
}: {
  proj: RevenueProjection;
}) {
  const monthlyTotal = proj.scenarios.reduce((acc, s) => acc + s.monthly_aed, 0);
  const roiMultiple = proj.agent_cost_aed > 0 ? monthlyTotal / proj.agent_cost_aed : 0;
  return (
    <Section
      idx="VI"
      label="the math"
      right={<span>revenue projection · grounded in your data</span>}
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
        }}
      >
        What you&apos;d earn back{" "}
        <em style={{ color: "#2d8e7d" }}>in month one.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "var(--paper-mut, #514c40)",
          margin: "0 0 18px",
          lineHeight: 1.55,
        }}
      >
        Conservative arithmetic from numbers we actually have on you. Not projections from a
        deck — line items you can argue with.
      </p>

      {/* Ground truth pills */}
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: 8,
          marginBottom: 18,
        }}
      >
        {proj.ground_truth.map((t, i) => (
          <span
            key={i}
            style={{
              display: "inline-flex",
              alignItems: "baseline",
              gap: 6,
              padding: "5px 12px",
              background: "var(--paper, #f6f3eb)",
              border: "1px solid var(--paper-line, #d8d2bf)",
              borderRadius: 999,
              fontSize: 12,
            }}
          >
            <span
              style={{
                fontFamily: MONO,
                fontSize: 10,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: "var(--paper-mut, #837c69)",
              }}
            >
              {t.k}
            </span>
            <span
              style={{
                fontFamily: SERIF,
                fontSize: 14,
                color: "var(--paper-ink, #1d1c18)",
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {t.v}
            </span>
          </span>
        ))}
      </div>

      {/* Scenario rows */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: 10,
          marginBottom: 18,
        }}
      >
        {proj.scenarios.map((s, i) => (
          <div
            key={i}
            style={{
              display: "grid",
              gridTemplateColumns: "1fr auto",
              gap: 12,
              padding: "14px 16px",
              background: "var(--paper, #f6f3eb)",
              border: "1px solid var(--paper-line, #d8d2bf)",
              borderRadius: 8,
              alignItems: "baseline",
            }}
          >
            <div>
              <div
                style={{
                  fontSize: 15,
                  fontWeight: 600,
                  marginBottom: 4,
                  color: "var(--paper-ink, #1d1c18)",
                }}
              >
                {s.name}
              </div>
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 12,
                  color: "var(--paper-mut, #514c40)",
                }}
              >
                {s.math}
              </div>
            </div>
            <div style={{ textAlign: "right" }}>
              <div
                style={{
                  fontFamily: SERIF,
                  fontSize: 26,
                  color: "#1e6d3d",
                  lineHeight: 1,
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                AED {s.monthly_aed.toLocaleString()}
              </div>
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 9,
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color:
                    s.confidence === "conservative"
                      ? "var(--paper-mut, #837c69)"
                      : s.confidence === "moderate"
                        ? "#a07232"
                        : "#2d8e7d",
                  marginTop: 4,
                }}
              >
                {s.confidence}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Totals */}
      <div
        style={{
          padding: "18px 20px",
          background: "#1d1c18",
          color: "#fbfaf4",
          borderRadius: 8,
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
          gap: 14,
          alignItems: "baseline",
        }}
      >
        <div>
          <div
            style={{
              fontFamily: MONO,
              fontSize: 10,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              opacity: 0.6,
              marginBottom: 6,
            }}
          >
            Conservative
          </div>
          <div
            style={{
              fontFamily: SERIF,
              fontSize: 30,
              lineHeight: 1,
              fontVariantNumeric: "tabular-nums",
            }}
          >
            AED {proj.total_conservative_aed.toLocaleString()}
            <span style={{ fontFamily: MONO, fontSize: 12, opacity: 0.6, marginLeft: 6 }}>
              /mo
            </span>
          </div>
        </div>
        <div>
          <div
            style={{
              fontFamily: MONO,
              fontSize: 10,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              opacity: 0.6,
              marginBottom: 6,
            }}
          >
            Optimistic
          </div>
          <div
            style={{
              fontFamily: SERIF,
              fontSize: 30,
              lineHeight: 1,
              fontVariantNumeric: "tabular-nums",
              color: "#4ade80",
            }}
          >
            AED {proj.total_optimistic_aed.toLocaleString()}
            <span style={{ fontFamily: MONO, fontSize: 12, opacity: 0.6, marginLeft: 6 }}>
              /mo
            </span>
          </div>
        </div>
        <div>
          <div
            style={{
              fontFamily: MONO,
              fontSize: 10,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              opacity: 0.6,
              marginBottom: 6,
            }}
          >
            ROI
          </div>
          <div
            style={{
              fontFamily: SERIF,
              fontSize: 30,
              lineHeight: 1,
              fontVariantNumeric: "tabular-nums",
              color: "#fbbf24",
            }}
          >
            {roiMultiple.toFixed(1)}×
            <span style={{ fontFamily: MONO, fontSize: 12, opacity: 0.6, marginLeft: 6 }}>
              vs AED {proj.agent_cost_aed.toLocaleString()}/mo
            </span>
          </div>
        </div>
      </div>
    </Section>
  );
}

/* ─── 7. ChannelMapCard ─── */

export function ChannelMapCard({
  map,
  agentName,
}: {
  map: ChannelMap;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="VII"
      label="every channel · one brain"
      right={<span>multi-channel orchestrator</span>}
      dark
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
          color: "#f3f1ea",
        }}
      >
        One {firstName}. Every surface your customers use.
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "rgba(255,255,255,0.7)",
          margin: "0 0 22px",
          lineHeight: 1.55,
          maxWidth: 540,
        }}
      >
        {map.unique_value}
      </p>

      <div style={{ position: "relative", padding: "16px 0 24px" }}>
        {/* Brain hub */}
        <div
          style={{
            margin: "0 auto",
            width: 130,
            padding: "14px 16px",
            background: "linear-gradient(180deg, #2d8e7d 0%, #1e6d6f 100%)",
            borderRadius: 999,
            color: "#fff",
            textAlign: "center",
            fontFamily: SERIF,
            fontSize: 17,
            fontStyle: "italic",
            boxShadow: "0 6px 20px rgba(45,142,125,0.32)",
          }}
        >
          {firstName} · brain
        </div>

        {/* Channel grid */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
            gap: 12,
            marginTop: 22,
          }}
        >
          {map.channels.map((ch) => (
            <div
              key={ch.name}
              style={{
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: 8,
                padding: "12px 14px",
                opacity: ch.status === "coming" ? 0.55 : 1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: 6,
                }}
              >
                <span
                  style={{
                    fontFamily: SERIF,
                    fontSize: 17,
                    color: "#f3f1ea",
                  }}
                >
                  {ch.name}
                </span>
                <span
                  style={{
                    fontFamily: MONO,
                    fontSize: 9,
                    letterSpacing: "0.14em",
                    textTransform: "uppercase",
                    color:
                      ch.status === "live"
                        ? "#4ade80"
                        : ch.status === "ready"
                          ? "#fbbf24"
                          : "rgba(255,255,255,0.4)",
                    fontWeight: 600,
                  }}
                >
                  ● {ch.status}
                </span>
              </div>
              <div
                style={{
                  fontFamily: MONO,
                  fontSize: 10,
                  letterSpacing: "0.06em",
                  color: "rgba(255,255,255,0.55)",
                  marginBottom: 6,
                }}
              >
                {ch.inbound_rate_estimate}
              </div>
              <p
                style={{
                  fontSize: 12,
                  lineHeight: 1.5,
                  color: "rgba(255,255,255,0.78)",
                  margin: 0,
                }}
              >
                {ch.sample_action}
              </p>
            </div>
          ))}
        </div>
      </div>
    </Section>
  );
}

/* ─── 8. NightlyLearningCard ─── */

export function NightlyLearningCard({
  learning,
  agentName,
}: {
  learning: NightlyLearning;
  agentName: string;
}) {
  const firstName = agentName.split(/\s+/)[0] || agentName;
  return (
    <Section
      idx="VIII"
      label="what happens overnight"
      right={<span>karpathy loop · self-improving</span>}
      dark
    >
      <h3
        style={{
          fontFamily: SERIF,
          fontSize: 28,
          fontWeight: 400,
          margin: "0 0 14px",
          lineHeight: 1.15,
          color: "#f3f1ea",
        }}
      >
        {firstName} doesn&apos;t sleep.{" "}
        <em style={{ color: "#4ade80" }}>She gets smarter while you do.</em>
      </h3>
      <p
        style={{
          fontSize: 14,
          color: "rgba(255,255,255,0.7)",
          margin: "0 0 22px",
          lineHeight: 1.55,
          maxWidth: 540,
        }}
      >
        Every night, every conversation gets re-read. Patterns that worked get promoted into
        rules. Rules get A/B verified against past chats before they ever touch a customer.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        {learning.timeline.map((step, i) => (
          <div
            key={i}
            style={{
              display: "grid",
              gridTemplateColumns: "70px 14px 1fr",
              gap: 12,
              padding: "10px 0",
              alignItems: "baseline",
              borderBottom:
                i < learning.timeline.length - 1
                  ? "1px dashed rgba(255,255,255,0.08)"
                  : "none",
            }}
          >
            <span
              style={{
                fontFamily: MONO,
                fontSize: 13,
                color: "#4ade80",
                letterSpacing: "0.06em",
                fontWeight: 600,
              }}
            >
              {step.time}
            </span>
            <span
              style={{
                width: 6,
                height: 6,
                borderRadius: "50%",
                background: "#4ade80",
                alignSelf: "center",
              }}
            />
            <div>
              <div
                style={{
                  fontFamily: SERIF,
                  fontSize: 16,
                  color: "#f3f1ea",
                  marginBottom: 2,
                }}
              >
                {step.label}
              </div>
              <p
                style={{
                  fontSize: 12.5,
                  lineHeight: 1.55,
                  margin: 0,
                  color: "rgba(255,255,255,0.65)",
                }}
              >
                {step.detail}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Example rule cards */}
      <div
        style={{
          marginTop: 22,
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          gap: 12,
        }}
      >
        <div
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 6,
            padding: "12px 14px",
          }}
        >
          <div
            style={{
              fontFamily: MONO,
              fontSize: 9,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "#fbbf24",
              marginBottom: 4,
            }}
          >
            Rule drafted at 02:00
          </div>
          <p
            style={{
              fontFamily: SERIF,
              fontStyle: "italic",
              fontSize: 14,
              margin: 0,
              color: "#f3f1ea",
              lineHeight: 1.45,
            }}
          >
            {learning.example_rule_drafted}
          </p>
        </div>
        <div
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 6,
            padding: "12px 14px",
          }}
        >
          <div
            style={{
              fontFamily: MONO,
              fontSize: 9,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "#4ade80",
              marginBottom: 4,
            }}
          >
            Verified at 04:00
          </div>
          <p
            style={{
              fontFamily: SERIF,
              fontStyle: "italic",
              fontSize: 14,
              margin: 0,
              color: "#f3f1ea",
              lineHeight: 1.45,
            }}
          >
            {learning.example_rule_verified}
          </p>
        </div>
      </div>

      <p
        style={{
          marginTop: 18,
          fontFamily: SERIF,
          fontSize: 17,
          fontStyle: "italic",
          color: "#f3f1ea",
        }}
      >
        ↳ {learning.result}
      </p>
    </Section>
  );
}

/* ─── Orchestrating renderer ─── */

export function PlatformDemoSections({
  demo,
  persona,
}: {
  demo: PlatformDemo;
  persona: AgentPersona;
}) {
  const name = persona.name;
  return (
    <>
      {demo.customer_memory && <CustomerMemoryCard memory={demo.customer_memory} agentName={name} />}
      {demo.owner_brief && <OwnerBriefCard brief={demo.owner_brief} agentName={name} />}
      {demo.voice_demo && <VoiceNoteDemoCard demo={demo.voice_demo} agentName={name} />}
      {demo.b2b_pipeline && demo.b2b_pipeline.leads.length > 0 && (
        <B2BPipelineCard pipeline={demo.b2b_pipeline} agentName={name} />
      )}
      {demo.seven_day_plan && demo.seven_day_plan.days.length > 0 && (
        <SevenDayPlanCard plan={demo.seven_day_plan} agentName={name} />
      )}
      {demo.revenue_projection && demo.revenue_projection.scenarios.length > 0 && (
        <RevenueProjectionCard proj={demo.revenue_projection} />
      )}
      {demo.channel_map && demo.channel_map.channels.length > 0 && (
        <ChannelMapCard map={demo.channel_map} agentName={name} />
      )}
      {demo.nightly_learning && demo.nightly_learning.timeline.length > 0 && (
        <NightlyLearningCard learning={demo.nightly_learning} agentName={name} />
      )}
    </>
  );
}
