-- Public teardowns: persistent, shareable analyses of UAE/Saudi SMB websites
-- generated by /api/teardown without authentication. The slug is the
-- permalink ID; the package field holds the full TeardownPackage JSON the
-- /teardown/[slug] page renders.
--
-- view_count is incremented on every public render so we can see which
-- teardowns are gaining traction (and reward the prospect with their own
-- traffic numbers if they sign up).

CREATE TABLE IF NOT EXISTS public_teardowns (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug            text NOT NULL UNIQUE,
  url             text NOT NULL,
  business_name   text NOT NULL,
  country         text CHECK (country IN ('AE', 'SA')),
  package         jsonb NOT NULL,
  -- Optional: the IP that requested the teardown. Lets us rate-limit and
  -- audit abuse. Stored as inet for cheap subnet lookups.
  source_ip       inet,
  view_count      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  last_viewed_at  timestamptz
);

-- Lookup by URL so the same URL doesn't regenerate on every paste —
-- the form can offer to show the existing teardown or refresh it.
CREATE INDEX IF NOT EXISTS public_teardowns_url_idx ON public_teardowns (url);

-- Recent-teardowns showcase on the marketing page.
CREATE INDEX IF NOT EXISTS public_teardowns_created_at_idx
  ON public_teardowns (created_at DESC);

-- Rate-limiting by IP.
CREATE INDEX IF NOT EXISTS public_teardowns_source_ip_idx
  ON public_teardowns (source_ip, created_at DESC);

GRANT SELECT, INSERT, UPDATE ON public_teardowns TO agents_app;
